name: npm setup
description: GitHub Action to automate the installation of npm dependencies for Angular projects
author: Samuel Fernández <https://github.com/samuelfernandez>
inputs:
  nx-key:
    required: false
    description: Caches NX local execution cache instead of relying on NX Cloud, this param is the key to uniquely identify a job that runs a NX script.
runs:
  using: node16
  main: dist/main/index.js
  post-if: success()
  post: dist/post/index.js
branding:
  icon: package
  color: green
